# Welcome to Jekyll!
# port: 8008
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
dev: nDang

# Site settings
title: jekyllionic
description: Deskripsi singkat tentang website Anda
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: vildaesa
license: "aHR0cHM6Ly92aWxkYWVzYS5naXRodWIuaW8="
image: /assets/images/logo-og.jpg   # default OG image
logo: /assets/images/logo-square.jpg # untuk JSON-LD
twitter_username: akun_twitter
favicon: /favicon.ico

# Markdown settings
markdown: kramdown
excerpt_separator: <!--more-->

permalink: /:title

# Sass settings
sass:
  add_charset: true
  sass_dir: _sass
  style: :compressed

# Custom Collections
collections:
  products:
    output: true
    
# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - functions

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-dotenv

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    categories: '/category/:name/'
    tags: '/tag/:name/'

WA_KEY: 6281111191209
CLIENT_KEY: "<%= ENV['CLIENT_KEY'] %>"
# Firebase
API_KEY: "<%= ENV['API_KEY'] %>"
AUTH_DOMAIN: "<%= ENV['AUTH_DOMAIN'] %>"
PROJECT_ID: "<%= ENV['PROJECT_ID'] %>"
DATABASE_URL: "<%= ENV['DATABASE_URL'] %>"
STORAGE_BUCKET: "<%= ENV['STORAGE_BUCKET'] %>"
SENDER_ID: "<%= ENV['SENDER_ID'] %>"
APP_ID: "<%= ENV['APP_ID'] %>"
