source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-feed'
gem 'jekyl-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-archives'
gem 'jekyll-paginate'
gem 'wdm', '>= 0.1.0'
gem 'jekyll-dotenv', '~> 0.1.0'
